name: Build Signed Release APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - uses: actions/checkout@v3

    # 2. Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 3. Setup Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true

    # 4. Install Dependencies
    - name: Install dependencies
      run: flutter pub get

    # 5. Decode Keystore (This creates the file android/app/upload-keystore.jks)
    - name: Decode Keystore
      run: |
        echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

    # 6. Build Signed Release APK
    - name: Build Signed APK
      run: flutter build apk --release
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    # 7. Upload the Signed APK
    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: SMSindia New Release
        path: build/app/outputs/flutter-apk/app-release.apk
        # 8. Send APK to Telegram Group
    - name: Send APK to Telegram
      run: |
        curl -F document=@build/app/outputs/flutter-apk/app-release.apk \
        -F chat_id=${{ secrets.TELEGRAM_TO }} \
        https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
        
        
    - name: Telegram Announcement
      run: |
        curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_TO }} \
        -d text="ğŸ‰ *NEW APK BUILD SUCCESSFULLY RELEASED!* ğŸš€%0A%0AğŸ“¦ Project: *SMSIndia*%0AğŸ” Signed Release APK%0Aâš™ï¸ Built via GitHub Actions%0A%0Aâœ… APK has been uploaded above.%0AğŸ”¥ Please test & deploy.%0A%0AğŸ˜„ Happy Building!" \
        -d parse_mode=Markdown
